theme: jekyll-theme-cayman
title: HL7 MLLP Mock Server
description: A lightweight mock server for HL7 v2 messages over MLLP — always-ACK, always-NACK, and rule-based smart handler
baseurl: ""
url: "https://hl7-mllp-mock-server.novalagung.com"
